import fs from 'fs';
import * as yml from 'js-yaml';

export interface OutputDefinition {
  description?: string;
}

export function output<T, V>(
  outputDef: OutputDefinition = { description: '' }
) {
  return function (target: any, ctx: ClassFieldDecoratorContext<T, V>) {
    const outputName = ctx.name.toString();
    return function (this: T, value: any) {
      if (process.env.GENERATE_ACTION_YML) {
        generateOutputYml(outputName, outputDef);
        return;
      }
      return value;
    };
  };
}

function generateOutputYml(outputName: string, outputDef: OutputDefinition) {
  const filePath = process.env.ACTION_YML_PATH as string;
  const doc = yml.load(fs.readFileSync(filePath, 'utf-8')) as any;
  doc.outputs = doc.outputs ?? {};
  doc.outputs[outputName] = {};
  if (outputDef.description) {
    doc.outputs[outputName].description = outputDef.description.replaceAll(
      '      ',
      ''
    );
  }

  const ymlString = '# This file is generated by typescript\n' + yml.dump(doc);
  fs.writeFileSync(filePath, ymlString, 'utf-8');
}
